### PR TITLE
Ja/database models

### PR DESCRIPTION
**Pull request by Johnny-Arroyo**
## Summary

Please provide a short summary about the changes in this pull request.

created models/schemas

## Related Issue

Link to the related issue (if applicable).
N/A

## Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Testing Steps

Describe how can this PR be tested.

npm run dev

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by Ponch49 — APPROVED** [review]
lgtm

**Review by jonbingkim — APPROVED** [review]
lgtm

**Review by robertstipp — APPROVED** [review]
Lets go

**Review by Joel-Christopher — COMMENTED** [review]
Looks great

**Pull request merged**
